---
#
## Ansible Role For deploying one shard, designed to be called in parallel

- name: Deploy Shard
  hosts: "{{ host }}"
  gather_facts: true
  vars_files:
   - group_vars/all.yml
   - group_vars/passwords.yml

  tasks:
   - name: Deploy Shard
     include: "tasks/deploy-shard.yml shard_name={{ name }} \
            dir=/home/{{ username }}/{{ name }} \
            port_num={{ port }} \
            gamemode=0"
