---
#
## Ansible Role For deploying one shard, designed to be called in parallel

- name: Deploy Server
  hosts: "{{ host }}"
  gather_facts: true
  vars_files:
   - variables/all.yml

  tasks:
   - name: Include variables
     include_vars:
       dir: variables

   - name: Update SQL
     include: "tasks/setup-sql.yml"

   - name: Deploy Server
     include: "tasks/deploy-server.yml
