---
#
## Ansible Role For shutting down the server, backing it up, updating it and restarting it

- name: Deploy Server
  hosts: "{{ host }}"
  gather_facts: true
  vars_files:
   - variables/all.yml

  tasks:
   - name: Include variables
     include_vars:
       dir: variables

   - name: Update SQL
     include: "tasks/setup-sql.yml"
     when: "{{ do_deploy | default('false') }}"
     include: "tasks/deploy-server.yml"

   - name: Warn restart
     include: "tasks/warn-restart.yml"
     when: "{{ do_warn10 | default('false') }}"

   - name: Stop server
     include: "tasks/stop-server.yml"
     when: "{{ do_stopminecraft | default('false') }}"

   - name: Backup server
     include: "tasks/backup-server.yml"
     when: "{{ do_backup | default('false') }}"

   - name: Deploy Server
     include: "tasks/deploy-server.yml"
     when: "{{ do_update | default('false') }}" or "{{ do_deploy | default('false') }}"

   - name: Start Server
     include: "tasks/start-server.yml"
     when: "{{ do_startminecraft | default('false') }}"
