#Delete backups in a given path based on a retention policy

- name: Collect older backups
  find:
    paths: "{{ backup_cull_path }}"
    age: "{{ backup_retention_time }}"
    file_type: file
    patterns: '*.tar.gz'
  register: outdated_backups

- name: Delete older backups
  file:
    path: "{{ item.path }}" 
    state: absent
  loop: "{{ (outdated_backups.files | sort(attribute='ctime'))[:- backup_retention_count ] | list }}"
  when: ('%Y-%m-%d %H:%M:%S' | ( strftime ( item.ctime | int ) ) | to_datetime).day != 1
