- name: Check if Spigot exists
  stat:
    path: "{{ main_folder }}/BuildTools/spigot-{{ mc_version }}.jar"
  register: spigot_exist

- name: Build Spigot if necessary
  include: "tasks/build-spigot.yml"
  when: spigot_exist.stat.exists == False

- name: "Copy {{ servername }} Spigot.jar"
  copy: "src={{ main_folder }}/BuildTools/spigot-{{ mc_version }}.jar dest={{ full_server_folder }}/{{ server_jar }}.jar owner={{ username }}"
