---
#task to deploy a single shard

- name: "Create {{ shard_name }} Directory"
  file: "path={{ dir }} state=directory owner={{ username }} mode=0755"

- name: "Create {{ shard_name }} Plugins Directory"
  file: "path={{ dir }}/plugins state=directory owner={{ username }} mode=0755"

- name: "Copy {{ shard_name }} top level public templates"
  template: "src={{ templates }}public/{{ item }}.j2 dest={{ dir }}/{{ item }} \
             owner={{ username }} mode='u=rw,g=r,o=r'"
  with_items: "{{ top_level_templates }}"

- name: "Copy {{ shard_name }} top level private templates"
  template: "src={{ templates }}private/{{ item }}.j2 dest={{ dir }}/{{ item }} \
             owner={{ username }} mode='u=rw,g=r,o=r'"
  with_items: "{{ secret_top_level_templates }}"
  when: groups["secret_top_level_templates"] is defined

- name: Deploy Spigot
  include: "tasks/deploy-spigot.yml"
  when: not use_paper

- name: Deploy Paper
  include: "tasks/deploy-paper.yml"
  when: use_paper

- name: "Clean existing Jarfiles"
  shell: "rm {{ dir }}/plugins/*.jar"
  ignore_errors: true

- name: "Deploy {{ shard_name }} plugins"
  include: "tasks/deploy-plugin.yml plugin_name={{ item }} plugin_dir=plugins"
  with_items: "{{ plugins }}"


#This is sometimes needed on new installation to make mysql play nicely
- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  become: yes

- name: Create `/home/{{ username }}/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /home/{{ username }}/.my.cnf
    owner: root
    mode: 0600
  become: yes

- name: Restart MariaDB and ensure it starts on boot
  service:
    name: mariadb
#    state: restarted
    enabled: yes
  become: yes


- name: "Create {{ mysql_db_name }} Database"	
  mysql_db: "name={{ mysql_db_name }} state=present login_user=root login_password={{ mysql_root_pass }} login_unix_socket={{ mysql_socket_location }} encoding=latin1"

- name: "Create {{ mysql_user }} MariaDB user"
  mysql_user: "name={{ mysql_user }} password={{ mysql_non_root_pass }} login_password={{ mysql_root_pass }} login_unix_socket={{ mysql_socket_location }} priv={{ mysql_db_name }}.*:ALL host=localhost state=present login_user=root"
