---
# Ansbile task to extract a single region file


- name: Get all backups
  find:
    paths: "{{ main_folder }}/{{ backups_folder }}/"
    file_type: file
    patterns: '*.tar.gz'
  register: found_backups

- name: Sort backups
  set_fact:
    sorted_backups: "{{ found_backups.files | sort(attribute='mtime',reverse=true) }}"

- name: Get backup by index
  set_fact:
    latest_backup: "{{ sorted_backups [{{ backup_go_back_count }}] }}"


- name: "Extracting region file"
  warn: false
  shell: "tar -zxvf {{ latest_backup.path }} {{ full_server_folder }}/{{ region_world }}/region/r.{{ region_x }}.{{ region_z }}.mca --force-local --strip-components 6 -C {{ full_server_folder }}/{{ region_world }}/region/ --transform='flags=r;s|r.{{ region_x }}.{{ region_z }}.mca|r.{{ target_region_x }}.{{ target_region_z }}.mca|'"




