#This is sometimes needed on new installation to make mysql play nicely
- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  become: yes

- name: Create `/home/{{ username }}/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /home/{{ username }}/.my.cnf
    owner: root
    mode: 0600
  become: yes

- name: Restart MariaDB and ensure it starts on boot
  service:
    name: mariadb
#    state: restarted
    enabled: yes
  become: yes


- name: "Create {{ mysql_db_name }} Database"	
  mysql_db: "name={{ mysql_db_name }} state=present login_user=root login_password={{ mysql_root_pass }} login_unix_socket={{ mysql_socket_location }} encoding=latin1"

- name: "Create {{ mysql_user }} MariaDB user"
  mysql_user: "name={{ mysql_user }} password={{ mysql_non_root_pass }} login_password={{ mysql_root_pass }} login_unix_socket={{ mysql_socket_location }} priv={{ mysql_db_name }}.*:ALL host=localhost state=present login_user=root"
