---
#task to restart shards

- name: Wait for Shard to stop
  wait_for: "port={{ internal_port }} state=absent"

- name: Send Start command
  shell: "tmux send -t {{ byobu_server_tab }} ENTER 'bash {{ startup_script }}' ENTER" 

- name: Wait for Shard to start
  wait_for: "port={{ internal_port }} state=present"
